okta:
    base-url: ${OKTA_BASE_URL}

spring:
    application:
        name: SpringSocialOauth2Demo
    security:
        oauth2:
            client:
                provider:
                    okta:
                        authorization-uri: ${OKTA_BASE_URL}/oauth2/v1/authorize
                        token-uri: ${OKTA_BASE_URL}/oauth2/v1/token
                        user-info-uri: ${OKTA_BASE_URL}/oauth2/v1/userinfo
                        jwk-set-uri: ${OKTA_BASE_URL}/oauth2/v1/keys
                        user-name-attribute: sub
                    gitlab:
                        authorization-uri: https://gitlab.com/oauth/authorize
                        token-uri: https://gitlab.com/oauth/token
                        user-info-uri: https://gitlab.com/api/v4/user
                        jwk-set-uri: https://gitlab.com/oauth/discovery/keys
                        user-name-attribute: username
                    taxis:
                        authorization-uri: https://test.gsis.gr/oauth2server/oauth/authorize
                        token-uri: https://test.gsis.gr/oauth2server/oauth/token
                        user-info-uri: https://test.gsis.gr/oauth2server/userinfo?format=xml
                registration:
                    github:
                        client-id: ${GITHUB_CLIENT_ID}
                        client-secret: ${GITHUB_CLIENT_SECRET}
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                    okta:
                        client-id: ${OKTA_CLIENT_ID}
                        client-secret: ${OKTA_CLIENT_SECRET}
                    gitlab:
                        client-id: ${GITLAB_CLIENT_ID}
                        client-secret: ${GITLAB_CLIENT_SECRET}
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8080/login/oauth2/code/gitlab
                        scope: read_user
#                        client-name: GitLab
                    taxis:
                        client-id: ${TAXIS_CLIENT_ID}
                        client-secret: ${TAXIS_CLIENT_SECRET}
                        authorization-grant-type: authorization_code
                        redirect-uri: ${TAXIS_REDIRECT_URI}
                        scope: read
        user:
            name: user
            password: password
